name: Firmware Build

on:
  workflow_run:
    workflows: ["Firmware Security Analysis"]
    types:
      - completed

jobs:
  build:
    # Only build if Static Analysis succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout triggering commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          submodules: recursive

      - name: Build firmware
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v6.1
          target: esp32
          command: idf.py build
