name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run Cppcheck Analysis
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v6.1
          target: esp32
          command: |
            apt-get update && apt-get install -y cppcheck
            cppcheck --enable=all --suppress=missingIncludeSystem ./main --error-exitcode=1

      - name: Build ESP-IDF project
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v6.1
          target: esp32
